const char* TEMPLATE =
"Not mustache has no strict requirements for the design of templating engines.\n"
"The engine included with this project uses a buffered callback system, in which\n"
"a stream object (mustache_stream) copies data from a stream into the input buffer\n"
"fed as an argument into mustache_parse_stream or mustache_parse_file.\n"
"These input chunks are processed by the template engine and fed into the parseCallback argument of\n"
"mustache_parse_stream or mustache_parse_file. This processed data will be stored in the output buffer.\n"
"\n"
"The mustache_structure is an opaque object type used to cache the structure of template. It improves performance\n"
"by converting the template in a binary format instead of re-parsing the source template every call.\n"
"To generate this structure, memory is allocated with parser_alloc and parser_free. It is automatically\n"
"generated on its first usage and will be reused in every subsequent parse.\n"
"Call structure_chain_flush to clear a structure chain if any of the following used to generate it\n"
"have changed:\n"
"- the source template\n"
"- parameter addresses\n"
"- parameter types\n"

"mustache_structure_chain_free MUST BE CALLED to free any memory allocated for a mustache_structure chain."
"\n"
"\n"
"Note that mustache_parse_file uses mustache_parse_stream internally, it only exists to\n"
"simplify the process of reading template files.\n"
"\n"
"\n"
"All chunks fed to this engine from a stream must contain only complete top-level scopes,\n"
"they cannot be split across chunks.\n"
"For example, /{{#mybool}} {{var}} {{/}} is valid,"
"but /{{#mybool}} {{var}} in one chunk and {{/}} in next is invalid.\n"
"\n"
"\n"
"This parsing engine does not do any significant checks on the validity of a not-mustache template;\n"
"it is not recommended that you use untrusted templates in this parsing engine.";